export const customers = [
  {
    id: 1,
    personType: 1,
    email: "john@email.com",
    name: "John",
    lastName: "Michael",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-1.jpg",
  },
  {
    id: 2,
    personType: 1,
    email: "alexa@email.com",
    name: "Alexa",
    lastName: "Liras",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-2.jpg",
  },
  {
    id: 3,
    personType: 2,
    email: "laurent@email.com",
    name: "Laurent",
    lastName: "Perrier",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-3.jpg",
  },
  {
    id: 4,
    personType: 2,
    email: "michael@email.com",
    name: "Michael",
    lastName: "Levi",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-4.jpg",
  },
  {
    id: 5,
    personType: 2,
    email: "richard@email.com",
    name: "Richard",
    lastName: "Gran",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-5.jpg",
  },
  {
    id: 6,
    personType: 2,
    email: "miriam@email.com",
    name: "Miriam",
    lastName: "Eric",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-6.jpg",
  },
  {
    id: 7,
    personType: 1,
    email: "john@email.com",
    name: "John",
    lastName: "Michael",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-8.jpg",
  },
  {
    id: 8,
    personType: 1,
    email: "alexa@email.com",
    name: "Alexa",
    lastName: "Liras",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-1.jpg",
  },
];
export const supplies = [
  {
    id: 1,
    personType: 1,
    email: "john@email.com",
    name: "John",
    lastName: "Michael",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-7.jpg",
  },
  {
    id: 2,
    personType: 1,
    email: "alexa@email.com",
    name: "Alexa",
    lastName: "Liras",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-8.jpg",
  },
  {
    id: 3,
    personType: 2,
    email: "laurent@email.com",
    name: "Laurent",
    lastName: "Perrier",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-1.jpg",
  },
  {
    id: 4,
    personType: 2,
    email: "michael@email.com",
    name: "Michael",
    lastName: "Levi",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-2.jpg",
  },
  {
    id: 5,
    personType: 2,
    email: "richard@email.com",
    name: "Richard",
    lastName: "Gran",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-3.jpg",
  },
  {
    id: 6,
    personType: 2,
    email: "miriam@email.com",
    name: "Miriam",
    lastName: "Eric",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpfCnpj: "123.456.789-23",
    rgIe: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-4.jpg",
  }
];
export const sallers = [
  {
    id: 1,
    email: "john@email.com",
    name: "John",
    lastName: "Michael",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-5.jpg",
  },
  {
    id: 2,
    email: "alexa@email.com",
    name: "Alexa",
    lastName: "Liras",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-6.jpg",
  },
  {
    id: 3,
    email: "laurent@email.com",
    name: "Laurent",
    lastName: "Perrier",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-7.jpg",
  },
  {
    id: 4,
    email: "michael@email.com",
    name: "Michael",
    lastName: "Levi",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-8.jpg",
  },
  {
    id: 5,
    email: "richard@email.com",
    name: "Richard",
    lastName: "Gran",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-1.jpg",
  },
  {
    id: 6,
    email: "miriam@email.com",
    name: "Miriam",
    lastName: "Eric",
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-2.jpg",
  }
];
export const brands = [
  {
    id: 1,
    name: "Hering",
    status: true,
  },
  {
    id: 2,
    name: "Privalia",
    status: false,
  },
  {
    id: 3,
    name: "Daffiti",
    status: false,
  },
  {
    id: 4,
    name: "Kanui",
    status: true,
  }
];
export const categories = [
  {
    id: 1,
    name: "Masculino",
    status: true,
  },
  {
    id: 2,
    name: "Feminino",
    status: true,
  },
  {
    id: 3,
    name: "Infantil Masculino",
    status: false,
  },
  {
    id: 4,
    name: "Infantil Feminino",
    status: true,
  }
];
export const colors = [
  {
    id: 1,
    name: "Vermelho",
    status: true,
  },
  {
  id: 2,
  name: "Amarelo",
  status: false,
  },
  {
  id: 3,
  name: "Branco",
  status: true,
  },
  {
    id: 4,
    name: "Verde",
    status: true,
  },
  {
    id: 5,
    name: "Rosa",
    status: false,
  }
];
export const sizes = [
  {
    id: 1,
    name: "PP",
    status: true,
  },
  {
    id: 2,
    name: "P",
    status: false,
  },
  {
    id: 3,
    name: "M",
    status: true,
  },
  {
    id: 4,
    name: "G",
    status: true,
  },
  {
    id: 5,
    name: "GG",
    status: true,
  },
  {
    id: 6,
    name: "XG",
    status: false,
  }
];
export const products = [
  {
    id: 1,
    sku: "BVFC879",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blaze com forrado costurado",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 87456-1234"},
    age: 16,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/blazer-vermelho.webp",
    medias: ["/img/produtos/feminino/blazer-vermelho.webp"],
  },
  {
    id: 2,
    sku: "BAFC64",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blaze com forrado costurado",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "Frederick Doe", mobile: "(11) 9 99451-1234"},
    age: 16,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/blazer-azul.webp",
    medias: ["/img/produtos/feminino/blazer-vermelho.webp"],
  },
  {
    id: 3,
    sku: "BAS64",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blusa de seda",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "Frederick Doe", mobile: "(11) 9 99451-1234"},
    age: 16,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/blusa-azul.webp",
    medias: ["/img/produtos/feminino/blusa-azul.webp"],
  },
  {
    id: 4,
    sku: "ACCS64",
    barCode: "A68JKCLA654987AKL",
    ncm: "65498796",
    title: "Calça lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/calca-amarela.webp",
    medias: ["/img/produtos/feminino/calca-amarela.webp"],
  },
  {
    id: 5,
    sku: "ACPP64",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Camisa lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/camisa-preta.jpg",
    medias: ["/img/produtos/feminino/camisa-preta.jpg"],
  },
  {
    id: 6,
    sku: "ALKSD09",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Cinto trançado premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 100,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/cinto-cinza.webp",
    medias: ["/img/produtos/feminino/cinto-cinza.webp"],
  },
  {
    id: 7,
    sku: "AJJKSD09",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Jaqueta lisa casual",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 100,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/jaqueta-vermelha.webp",
    medias: ["/img/produtos/feminino/jaqueta-vermelha.webp"],
  },
  {
    id: 8,
    sku: "ACPP64",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Saia lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/saia-vermelha.webp",
    medias: ["/img/produtos/feminino/saia-vermelha.webp"],
  },
  {
    id: 9,
    sku: "ACPP64",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Vestido lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/vestido-amarelo.webp",
    medias: ["/img/produtos/feminino/vestido-amarelo.webp"],
  },
  {
    id: 10,
    sku: "AJJKSD09",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Vestido lisa casual",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 100,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/produtos/feminino/vestido-roxo.webp",
    medias: ["/img/produtos/feminino/vestido-roxo.webp"],
  },
];
export const variates = [
  {
    productId: 1,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "M",
    minStock: 20,
    stock: 19,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 1,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "G",
    minStock: 20,
    stock: 29,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 2,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 2,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Preta",
    size: "G",
    minStock: 20,
    stock: 39,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 3,
    coast: 30.88,
    price: 58.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 3,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Preta",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 4,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Amarelo",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 5,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "M",
    minStock: 20,
    stock: 19,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 5,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "G",
    minStock: 20,
    stock: 29,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 6,
    coast: 30.88,
    price: 58.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 7,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "G",
    minStock: 20,
    stock: 29,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 8,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 9,
    coast: 30.88,
    price: 58.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 9,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Preta",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 9,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Amarelo",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 10,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  }
];

export const payments = [
  {
    id: 1,
    supply: { name: "John Michael", email: "john@email.com", image: "/img/avatar-3.jpg" },
    amount: 250.99,
    deadlineAt: "Fri Jun 16 2023",
    paymentAt: "",
    status: false,
  },
  {
    id: 2,
    supply: { name: "Miriam Eric", email: "miriam@email.com", image: "/img/avatar-4.jpg" },
    amount: 150.99,
    deadlineAt: "25 Agosto 2010",
    paymentAt: "30 Agosto 2010",
    status: true,
  },
  {
    id: 3,
    supply: { name: "Laurent Perret", email: "laurent@email.com", image: "/img/avatar-5.jpg" },
    amount: 290.99,
    deadlineAt: "Fri Jun 16 2024",
    paymentAt: "",
    status: false,
  },
];
export const sales = [
  {
    id: 1,
    customer: { name: "John Michael", email: "john@email.com", image: "/img/avatar-6.jpg" },
    saller: { name: "Jorjão do Anabol" },
    paymentMethod: "Crédito",
    createAt: "25 Agosto 2010",
  }
];
export const paymentsMethods = [
  {
    id: 1,
    name: "Crédito",
    status: true,
    installments: "12x sem juros",
  },
  {
    id: 2,
    name: "PIX",
    status: true,
    installments: "à vista",
  },
  {
    id: 3,
    name: "Cheque",
    status: true,
    installments: "6x vezes sem juros",
  },
  {
    id: 4,
    name: "Boleto",
    status: false,
    installments: "6x sem juros",
  },
  {
    id: 5,
    name: "Crediário",
    status: true,
    installments: "24x sem juros",
  }
];
export const users = [
  {
    id: 1,
    email: "john@email.com",
    name: "John",
    lastName: "Michael",
    profile: 1,
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-2.jpg",
  },
  {
    id: 2,
    email: "alexa@email.com",
    name: "Alexa",
    lastName: "Liras",
    profile: 1,
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-3.jpg",
  },
  {
    id: 3,
    email: "laurent@email.com",
    name: "Laurent",
    lastName: "Perrier",
    profile: 2,
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: true,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-4.jpg",
  },
  {
    id: 4,
    email: "michael@email.com",
    name: "Michael",
    lastName: "Levi",
    profile: 2,
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-3.jpg",
  },
  {
    id: 5,
    email: "richard@email.com",
    name: "Richard",
    lastName: "Gran",
    profile: 1,
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-2.jpg",
  },
  {
    id: 6,
    email: "miriam@email.com",
    name: "Miriam",
    lastName: "Eric",
    profile: 2,
    phone: "(11) 9 87456-1234",
    mobile: "(11) 9 87456-1234",
    cpf: "123.456.789-23",
    rg: "12364-897",
    birthday: "21/02/2000",
    address: "Rua do Jurandir Carrasco",
    city: "São Paulo",
    state: "São Paulo",
    neighborhood: "Bairro Principal",
    cep: "123456-789",
    number: 789,
    status: false,
    obs: "Lorem ipsum et dolor al",
    image: "/img/avatar-4.jpg",
  }
];