export const categories = ["Masculino", "Feminino", "Infantil Masculino", "Infantil Feminino"];
export const colors = ["Vermelho", "Amarelo", "Branco", "Verde", "Rosa"];
export const sizes = ["PP", "P", "M", "G", "GG", "XG"];
export const brands = ["Hering", "Privalia", "Daffiti", "Kanui"];
export const products = [
  {
    id: 1,
    sku: "BVFC879",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blaze com forrado costurado",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 87456-1234"},
    age: 16,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "/img/products/feminino/blazer-vermelho.webp",
    medias: ["/img/feminino/blazer-vermelho.webp"],
  },
  {
    id: 2,
    sku: "BAFC64",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blaze com forrado costurado",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "Frederick Doe", mobile: "(11) 9 99451-1234"},
    age: 16,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "/img/products/feminino/blazer-azul.webp",
    medias: ["/img/products/feminino/blazer-vermelho.webp"],
  },
  {
    id: 3,
    sku: "BAS64",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blusa de seda",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "Frederick Doe", mobile: "(11) 9 99451-1234"},
    age: 16,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "/img/products/feminino/blusa-azul.webp",
    medias: ["/img/products/feminino/blusa-azul.webp"],
  },
  {
    id: 4,
    sku: "ACCS64",
    barCode: "A68JKCLA654987AKL",
    ncm: "65498796",
    title: "Calça lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/calca-amarela.webp",
    medias: ["/img/products/feminino/calca-amarela.webp"],
  },
  {
    id: 5,
    sku: "ACPP64",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Camisa lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/camisa-preta.jpg",
    medias: ["/img/products/feminino/camisa-preta.jpg"],
  },
  {
    id: 6,
    sku: "ALKSD09",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Cinto trançado premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 100,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/cinto-cinza.webp",
    medias: ["/img/products/feminino/cinto-cinza.webp"],
  },
  {
    id: 7,
    sku: "AJJKSD09",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Jaqueta lisa casual",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 100,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/jaqueta-vermelha.webp",
    medias: ["/img/products/feminino/jaqueta-vermelha.webp"],
  },
  {
    id: 8,
    sku: "ACPP64",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Saia lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/saia-vermelha.webp",
    medias: ["/img/products/feminino/saia-vermelha.webp"],
  },
  {
    id: 9,
    sku: "ACPP64",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Vestido lisa premium",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 180,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/vestido-amarelo.webp",
    medias: ["/img/products/feminino/vestido-amarelo.webp"],
  },
  {
    id: 10,
    sku: "AJJKSD09",
    barCode: "A68JKCL98AS654987AKL",
    ncm: "68998796",
    title: "Vestido lisa casual",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "Feminino",
    brand: "Hering",
    supply: { name: "John Doe", mobile: "(11) 9 99451-1234"},
    age: 10,
    weight: 100,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "12 Fevereiro 2020",
    thumbnail: "/img/products/feminino/vestido-roxo.webp",
    medias: ["/img/products/feminino/vestido-roxo.webp"],
  },
];
export const variates = [
  {
    productId: 1,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "M",
    minStock: 20,
    stock: 19,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 1,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "G",
    minStock: 20,
    stock: 29,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 2,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 2,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Preta",
    size: "G",
    minStock: 20,
    stock: 39,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 3,
    coast: 30.88,
    price: 58.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 3,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Preta",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 4,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Amarelo",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 5,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "M",
    minStock: 20,
    stock: 19,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 5,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "G",
    minStock: 20,
    stock: 29,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 6,
    coast: 30.88,
    price: 58.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 7,
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelha",
    size: "G",
    minStock: 20,
    stock: 29,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 8,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 9,
    coast: 30.88,
    price: 58.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 9,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Preta",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 9,
    coast: 30.88,
    price: 78.99,
    discount: 35.79,
    color: "Amarelo",
    size: "G",
    minStock: 20,
    stock: 89,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
  {
    productId: 10,
    coast: 30.88,
    price: 48.99,
    discount: 35.79,
    color: "Azul",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  }
];

// {
//   SKU: "BAFC64",
//   CodigoBarra: "ASLDJKCLA654987AKL",
//   NCM: "65498726",
//   Nome: "Blaze azul com forrado costurado",
//   Descricao: "Lorem ipsum dolor sit amet",
//   Categoria: "feminino",
//   Marca: "Hering",
//   Fornecedor: "John Doe",
//   Cor: "Azul", "Amarelo",
//   Tamanho: "P", "M", "G",
//   Idade: 16,
//   Custo: 30.00,
//   Preco: 38.99,
//   Desconto: 35.00,
//   EstoqueMinino: 20,
//   Estoque: 79,
//   Peso: 200,
//   status: "Ativo",
//   Observacao: "Lorem ipsum dolor sit amet",
//   Capa: "blazer-azul.webp",
//   Imagens: "blazer-vermelho.webp",
// },