export const categories = ["Masculino", "Feminino", "Infantil Masculino", "Infantil Feminino"];
export const colors = ["Vermelho", "Amarelo", "Branco", "Verde", "Rosa"];
export const sizes = ["PP", "P", "M", "G", "GG", "XG"];
export const brands = ["Hering", "Privalia", "Daffiti", "Kanui"];
export const products = [
  {
    sku: "BVFC879",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blaze vermelho com forrado costurado",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "feminino",
    brand: "hering",
    supply: "John Doe",
    color: ["Vermelho"],
    size: ["M", "G", "GG"],
    age: 16,
    coast: 30.00,
    price: 38.99,
    discount: 35.00,
    minStock: 20,
    stock: 79,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "blazer-vermelho.webp",
    medias: ["blazer-vermelho.webp"],
  },
  {
    sku: "BAFC64",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blaze azul com forrado costurado",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "feminino",
    brand: "Hering",
    supply: "John Doe",
    color: ["Azul"],
    size: ["P", "M", "G"],
    age: 16,
    coast: 30.00,
    price: 38.99,
    discount: 35.00,
    minStock: 20,
    stock: 79,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "blazer-azul.webp",
    medias: ["blazer-vermelho.webp"],
  },
  {
    sku: "BAS64",
    barCode: "ASLDJKCLA654987AKL",
    ncm: "65498726",
    title: "Blusa azul de seda",
    description: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    category: "feminino",
    brand: "Hering",
    supply: "John Doe",
    color: ["Azul"],
    size: ["M", "G"],
    age: 16,
    coast: 30.00,
    price: 38.99,
    discount: 35.00,
    minStock: 20,
    stock: 79,
    weight: 200,
    status: true,
    obs: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae reprehenderit repellendus expedita esse cupiditate quos doloremque rerum, corrupti ab illum est nihil, voluptate ex dignissimos! Sit voluptatem delectus nam, molestiae, repellendus ab sint quo aliquam debitis amet natus doloremque laudantium? Repudiandae, consequuntur, officiis quidem quo deleniti, autem non laudantium sequi error molestiae ducimus accusamus facere velit consectetur vero dolore natus nihil temporibus aspernatur quia consequatur? Consequuntur voluptate deserunt repellat tenetur debitis molestiae doloribus dicta. In rem illum dolorem atque ratione voluptates asperiores maxime doloremque laudantium magni neque ad quae quos quidem, quaerat rerum ducimus blanditiis reiciendis",
    createdAt: "2 Fevereiro 2020",
    thumbnail: "blusa-azul.webp",
    medias: ["blusa-azul.webp"],
  }
];
export const variates = [
  {
    productId: "BVFC879",
    coast: 30.88,
    price: 38.99,
    discount: 35.79,
    color: "Vermelho",
    size: "M",
    minStock: 20,
    stock: 79,
    status: true,
    orders: 45,
    sales: 45000.99,
  },
];